### ISSUE TITLE
Sprites in embeddings visualizer are wrong?

### ISSUE THREAD

**Issue by mhyttsten** [dandelionmane/tf-dev-summit-tensorboard-tutorial#2]
It seems like the examples are clearly separated by the coding color, but the sprites displayed on seem randomly mixed around the colors. See screenshot.

![screen shot 2017-06-19 at 11 29 26 am](https://user-images.githubusercontent.com/5739464/27300758-a8349790-54e5-11e7-9a7b-a5dc51a18afe.jpg)

**Comment by AlexGfocus** [comment]
Because arrangement of sprits in sprite_1024.png is wrong. Please find correct picture in https://github.com/mamcgrath/TensorBoard-TF-Dev-Summit-Tutorial.

**Comment by teamdandelion** [comment]
Should be fixed now. Thanks @AlexGfocus
