### ISSUE TITLE
tf summary image 3?

### ISSUE THREAD

**Issue by henriquetmaia** [dandelionmane/tf-dev-summit-tensorboard-tutorial#7]
Hello! Great talk, and thanks for posting everything. Much appreciated!

I was wondering why you use:
`tf.summary.image('input', x_image, 3)`
when setting up the summary item for the input images from mnist.
Are they not grayscale 28 x 28 images? 
Why choose 3 (RGB), and why does it work?
Just looking for some intuition. Thanks again for the wonderful presentation.

**Comment by DocDriven** [comment]
Hello henriquetmaia,

you are right that those are grayscale images. According to the tf documentation (https://www.tensorflow.org/api_docs/python/tf/summary/image), the third argument is 'max_outputs' which controls the numbering of the image tags. Therefore, it has nothing to do with the number of channels.

I hope this helps!

**Comment by henriquetmaia** [comment]
That explains it. Thanks!
